//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.05 at 04:07:18 PM CET 
//


package it.gov.mef.noipa.postemissione.parser.autogenerated.cedolino.depcon;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.gov.mef.noipa.postemissione.parser.autogenerated.cedolino.depcon package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Main_QNAME = new QName("http://postemissione.noipa.mef.gov.it/parser/autogenerated/cedolino/depcon", "main");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.gov.mef.noipa.postemissione.parser.autogenerated.cedolino.depcon
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DettaglioAliquota }
     * 
     */
    public DettaglioAliquota createDettaglioAliquota() {
        return new DettaglioAliquota();
    }

    /**
     * Create an instance of {@link DettaglioAliquotaRitenuta }
     * 
     */
    public DettaglioAliquotaRitenuta createDettaglioAliquotaRitenuta() {
        return new DettaglioAliquotaRitenuta();
    }

    /**
     * Create an instance of {@link Totali }
     * 
     */
    public Totali createTotali() {
        return new Totali();
    }

    /**
     * Create an instance of {@link EnteAppartenenza }
     * 
     */
    public EnteAppartenenza createEnteAppartenenza() {
        return new EnteAppartenenza();
    }

    /**
     * Create an instance of {@link ImportiProgressivi }
     * 
     */
    public ImportiProgressivi createImportiProgressivi() {
        return new ImportiProgressivi();
    }

    /**
     * Create an instance of {@link Identificativo }
     * 
     */
    public Identificativo createIdentificativo() {
        return new Identificativo();
    }

    /**
     * Create an instance of {@link RIF }
     * 
     */
    public RIF createRIF() {
        return new RIF();
    }

    /**
     * Create an instance of {@link NPT }
     * 
     */
    public NPT createNPT() {
        return new NPT();
    }

    /**
     * Create an instance of {@link Detrazioni }
     * 
     */
    public Detrazioni createDetrazioni() {
        return new Detrazioni();
    }

    /**
     * Create an instance of {@link RiepilogoRetribuzione }
     * 
     */
    public RiepilogoRetribuzione createRiepilogoRetribuzione() {
        return new RiepilogoRetribuzione();
    }

    /**
     * Create an instance of {@link PosizioneGiuridicoEconomica }
     * 
     */
    public PosizioneGiuridicoEconomica createPosizioneGiuridicoEconomica() {
        return new PosizioneGiuridicoEconomica();
    }

    /**
     * Create an instance of {@link DettaglioRetribuzione }
     * 
     */
    public DettaglioRetribuzione createDettaglioRetribuzione() {
        return new DettaglioRetribuzione();
    }

    /**
     * Create an instance of {@link DettaglioCompetenzaRitenuta }
     * 
     */
    public DettaglioCompetenzaRitenuta createDettaglioCompetenzaRitenuta() {
        return new DettaglioCompetenzaRitenuta();
    }

    /**
     * Create an instance of {@link COV }
     * 
     */
    public COV createCOV() {
        return new COV();
    }

    /**
     * Create an instance of {@link CED2 }
     * 
     */
    public CED2 createCED2() {
        return new CED2();
    }

    /**
     * Create an instance of {@link Barcode }
     * 
     */
    public Barcode createBarcode() {
        return new Barcode();
    }

    /**
     * Create an instance of {@link DatiAnagrafici }
     * 
     */
    public DatiAnagrafici createDatiAnagrafici() {
        return new DatiAnagrafici();
    }

    /**
     * Create an instance of {@link Messaggio }
     * 
     */
    public Messaggio createMessaggio() {
        return new Messaggio();
    }

    /**
     * Create an instance of {@link RiepilogoRetribuzioneChoice }
     * 
     */
    public RiepilogoRetribuzioneChoice createRiepilogoRetribuzioneChoice() {
        return new RiepilogoRetribuzioneChoice();
    }

    /**
     * Create an instance of {@link Ritenute }
     * 
     */
    public Ritenute createRitenute() {
        return new Ritenute();
    }

    /**
     * Create an instance of {@link DettaglioCompetenzeRitenute }
     * 
     */
    public DettaglioCompetenzeRitenute createDettaglioCompetenzeRitenute() {
        return new DettaglioCompetenzeRitenute();
    }

    /**
     * Create an instance of {@link CED3 }
     * 
     */
    public CED3 createCED3() {
        return new CED3();
    }

    /**
     * Create an instance of {@link CedolinoDepcon }
     * 
     */
    public CedolinoDepcon createCedolinoDepcon() {
        return new CedolinoDepcon();
    }

    /**
     * Create an instance of {@link TestataEnte }
     * 
     */
    public TestataEnte createTestataEnte() {
        return new TestataEnte();
    }

    /**
     * Create an instance of {@link CompetenzeFisse }
     * 
     */
    public CompetenzeFisse createCompetenzeFisse() {
        return new CompetenzeFisse();
    }

    /**
     * Create an instance of {@link ImportiProgressiviME }
     * 
     */
    public ImportiProgressiviME createImportiProgressiviME() {
        return new ImportiProgressiviME();
    }

    /**
     * Create an instance of {@link IdentificativoPagina }
     * 
     */
    public IdentificativoPagina createIdentificativoPagina() {
        return new IdentificativoPagina();
    }

    /**
     * Create an instance of {@link EstremiPagamento }
     * 
     */
    public EstremiPagamento createEstremiPagamento() {
        return new EstremiPagamento();
    }

    /**
     * Create an instance of {@link RiemissionePerStorno }
     * 
     */
    public RiemissionePerStorno createRiemissionePerStorno() {
        return new RiemissionePerStorno();
    }

    /**
     * Create an instance of {@link DettaglioCompetenzeRitenuteChoice }
     * 
     */
    public DettaglioCompetenzeRitenuteChoice createDettaglioCompetenzeRitenuteChoice() {
        return new DettaglioCompetenzeRitenuteChoice();
    }

    /**
     * Create an instance of {@link CompetenzeAccessorieConguagli }
     * 
     */
    public CompetenzeAccessorieConguagli createCompetenzeAccessorieConguagli() {
        return new CompetenzeAccessorieConguagli();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CedolinoDepcon }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://postemissione.noipa.mef.gov.it/parser/autogenerated/cedolino/depcon", name = "main")
    public JAXBElement<CedolinoDepcon> createMain(CedolinoDepcon value) {
        return new JAXBElement<CedolinoDepcon>(_Main_QNAME, CedolinoDepcon.class, null, value);
    }

}
