package it.gov.mef.noipa.postemissione.parser.autogenerated.cedolino.depcon.types;

public class ContrattiVigentiType {

	private String recordValue;

	public ContrattiVigentiType(String recordValue) {
		super();
		this.recordValue = recordValue;
	}
	
	public String getDataDecorrenza(){
		int startingPosition = 0;
    	int length = 10;
    	return getSubString(startingPosition, length);
	}
	
	public String getDataScadenza(){
		int startingPosition = 10;
    	int length = 10;
    	return getSubString(startingPosition, length);
	}
	
	public String getOreSuCattedra(){
		int startingPosition = 20;
    	int length = 10;
    	return getSubString(startingPosition, length);
	}

	public String getCodSIDI(){
		int startingPosition = 30;
    	int length = 10;
    	return getSubString(startingPosition, length);
	}
	
	public String getTipologia(){
		int startingPosition = 40;
    	int length = recordValue.length();
    	return getSubString(startingPosition, length);
	}
	
	private String getSubString(int startingPosition, int length) {
		if(startingPosition<recordValue.length()){
    		return recordValue.substring(startingPosition,Math.min(startingPosition+length, recordValue.length())).trim();
    	}else{
    		return null;
    	}
	}

	
}
