
package it.gov.mef.noipa.postemissione.parser.autogenerated.cedolino.depcon.types;



public class DetrazioniType {

    protected String recordValue;

    public DetrazioniType(String recordValue) {
		super();
		this.recordValue = recordValue;
	}

	public String getRecordValue() {
        return recordValue;
    }

    public void setRecordValue(String value) {
        this.recordValue = value;
    }

    public String getLavoroDipendente(){
    	int startingPosition = 0;
    	int length = 9;
    	if(startingPosition<recordValue.length()){
    		return recordValue.substring(startingPosition,Math.min(startingPosition+length, recordValue.length()));
    	}else{
    		return null;
    	}
    	
    }
    
    public String getConiuge(){
    	int startingPosition = 9;
    	int length = 9;
    	if(startingPosition<recordValue.length()){
    		return recordValue.substring(startingPosition,Math.min(startingPosition+length, recordValue.length()));
    	}else{
    		return null;
    	}
    	
    }
    
    public String getNumeroFigli(){
    	int startingPosition = 18;
    	int length = 2;
    	if(startingPosition<recordValue.length()){
    		return recordValue.substring(startingPosition,Math.min(startingPosition+length, recordValue.length()));
    	}else{
    		return null;
    	}
    	
    }
    
    public String getDetrazioneFigli(){
    	int startingPosition = 20;
    	int length = 9;
    	if(startingPosition<recordValue.length()){
    		return recordValue.substring(startingPosition,Math.min(startingPosition+length, recordValue.length()));
    	}else{
    		return null;
    	}
    	
    }
    
    public String getNumeroAltriFamigliari(){
    	int startingPosition = 29;
    	int length = 2;
    	if(startingPosition<recordValue.length()){
    		return recordValue.substring(startingPosition,Math.min(startingPosition+length, recordValue.length()));
    	}else{
    		return null;
    	}
    	
    }
    
    public String getDetrazioneAltriFamigliari(){
    	int startingPosition = 31;
    	int length = 9;
    	if(startingPosition<recordValue.length()){
    		return recordValue.substring(startingPosition,Math.min(startingPosition+length, recordValue.length()));
    	}else{
    		return null;
    	}
    	
    }
    
    public String getNumeroFigliMinoiriDi3Anni(){
    	int startingPosition = 40;
    	int length = 2;
    	if(startingPosition<recordValue.length()){
    		return recordValue.substring(startingPosition,Math.min(startingPosition+length, recordValue.length()));
    	}else{
    		return null;
    	}
    	
    }
    
    public String getDetrazioneFigliMinoiriDi3Anni(){
    	int startingPosition = 42;
    	int length = 9;
    	if(startingPosition<recordValue.length()){
    		return recordValue.substring(startingPosition,Math.min(startingPosition+length, recordValue.length()));
    	}else{
    		return null;
    	}
    	
    }
    
    public String getTotale(){
    	int startingPosition = 51;
    	int length = 10;
    	if(startingPosition<recordValue.length()){
    		return recordValue.substring(startingPosition,Math.min(startingPosition+length, recordValue.length()));
    	}else{
    		return null;
    	}
    	
    }
    
}
