
package it.gov.mef.noipa.postemissione.parser.autogenerated.cedolino.depcon.types;



public class DettaglioAliquotaRitenutaType {

    protected String recordValue;

    public DettaglioAliquotaRitenutaType(String recordValue) {
		super();
		this.recordValue = recordValue;
	}

	public String getRecordValue() {
        return recordValue;
    }

    public void setRecordValue(String value) {
        this.recordValue = value;
    }

    public String getImponibile(){
    	int startingPosition = 0;
    	int length = 12;
    	if(startingPosition<recordValue.length()){
    		return recordValue.substring(startingPosition,Math.min(startingPosition+length, recordValue.length()));
    	}else{
    		return null;
    	}
    	
    }
    
    public String getAliquota(){
    	int startingPosition = 12;
    	int length = 6;
    	if(startingPosition<recordValue.length()){
    		return recordValue.substring(startingPosition,Math.min(startingPosition+length, recordValue.length()));
    	}else{
    		return null;
    	}
    	
    }
    
    public String getImporto(){
    	int startingPosition = 18;
    	int length = 13;
    	if(startingPosition<recordValue.length()){
    		return recordValue.substring(startingPosition,Math.min(startingPosition+length, recordValue.length()));
    	}else{
    		return null;
    	}
    	
    }
    
    public String getDescrizione(){
    	int startingPosition = 31;
    	int length = 50;
    	if(startingPosition<recordValue.length()){
    		return recordValue.substring(startingPosition,Math.min(startingPosition+length, recordValue.length()));
    	}else{
    		return null;
    	}
    	
    }
   
}
