
package it.gov.mef.noipa.postemissione.parser.autogenerated.cedolino.depcon.types;



public class DettaglioAliquotaType {

    protected String recordValue;

    public DettaglioAliquotaType(String recordValue) {
		super();
		this.recordValue = recordValue;
	}

	public String getRecordValue() {
        return recordValue;
    }

    public void setRecordValue(String value) {
        this.recordValue = value;
    }

    public String getImponibile(){
    	int startingPosition = 0;
    	int length = 10;
    	if(startingPosition<recordValue.length()){
    		return recordValue.substring(startingPosition,Math.min(startingPosition+length, recordValue.length()));
    	}else{
    		return null;
    	}
    	
    }
    
    public String getAliquota(){
    	int startingPosition = 10;
    	int length = 14;
    	if(startingPosition<recordValue.length()){
    		return recordValue.substring(startingPosition,Math.min(startingPosition+length, recordValue.length()));
    	}else{
    		return null;
    	}
    	
    }
    
    public String getImporto(){
    	int startingPosition = 24;
    	int length = 10;
    	if(startingPosition<recordValue.length()){
    		return recordValue.substring(startingPosition,Math.min(startingPosition+length, recordValue.length()));
    	}else{
    		return null;
    	}
    	
    }
    
    public String getDescrizione(){
    	int startingPosition = 34;
    	int length = 50;
    	if(startingPosition<recordValue.length()){
    		return recordValue.substring(startingPosition,Math.min(startingPosition+length, recordValue.length()));
    	}else{
    		return null;
    	}
    	
    }
   
}
