
package it.gov.mef.noipa.postemissione.parser.autogenerated.cedolino.depcon.types;


public class PosizioneGiuridicoEconomicaType {

    protected String recordId;

   public PosizioneGiuridicoEconomicaType(String recordId) {
		super();
		this.recordId = recordId;
	}

   public String getRecordId() {
        return recordId;
    }

    public void setRecordId(String value) {
        this.recordId = value;
    }
    
    public String getInquadramento(){
    	int startingPosition = 0;
    	int length = 30;
    	if(startingPosition<recordId.length()){
    		return recordId.substring(startingPosition,Math.min(startingPosition+length, recordId.length()));
    	}else{
    		return null;
    	}
    	
    }
    
    public String getQualifica(){
    	int startingPosition = 30;
    	int length = 4;
    	if(startingPosition<recordId.length()){
    		return recordId.substring(startingPosition,Math.min(startingPosition+length, recordId.length()));
    	}else{
    		return null;
    	}
    	
    }
    
    public String getScadenza(){
    	int startingPosition = 34;
    	int length = 10;
    	if(startingPosition<recordId.length()){
    		return recordId.substring(startingPosition,Math.min(startingPosition+length, recordId.length()));
    	}else{
    		return null;
    	}
    	
    }
    
    public String getTipoLiquidazione(){
    	int startingPosition = 44;
    	int length = 3;
    	if(startingPosition<recordId.length()){
    		return recordId.substring(startingPosition,Math.min(startingPosition+length, recordId.length()));
    	}else{
    		return null;
    	}
    	
    }
    
    public String getLivello(){
    	int startingPosition = 47;
    	int length = 3;
    	if(startingPosition<recordId.length()){
    		return recordId.substring(startingPosition,Math.min(startingPosition+length, recordId.length()));
    	}else{
    		return null;
    	}
    	
    }
    
    public String getParametro(){
    	int startingPosition = 50;
    	int length = 6;
    	if(startingPosition<recordId.length()){
    		return recordId.substring(startingPosition,Math.min(startingPosition+length, recordId.length()));
    	}else{
    		return null;
    	}
    	
    }
    
    public String getFascia(){
    	int startingPosition = 56;
    	int length = 2;
    	if(startingPosition<recordId.length()){
    		return recordId.substring(startingPosition,Math.min(startingPosition+length, recordId.length()));
    	}else{
    		return null;
    	}
    	
    }
    
    public String getScatto(){
    	int startingPosition = 58;
    	int length = 2;
    	if(startingPosition<recordId.length()){
    		return recordId.substring(startingPosition,Math.min(startingPosition+length, recordId.length()));
    	}else{
    		return null;
    	}
    	
    }
    
    public String getCassaPrevidenza(){
    	int startingPosition = 60;
    	int length = 8;
    	if(startingPosition<recordId.length()){
    		return recordId.substring(startingPosition,Math.min(startingPosition+length, recordId.length()));
    	}else{
    		return null;
    	}
    	
    }
    
    public String getAdesionePrevComplementare(){
    	int startingPosition = 68;
    	int length = 2;
    	if(startingPosition<recordId.length()){
    		return recordId.substring(startingPosition,Math.min(startingPosition+length, recordId.length()));
    	}else{
    		return null;
    	}
    	
    }
    
    public String getTipoRapporto(){
    	int startingPosition = 70;
    	int length = 40;
    	if(startingPosition<recordId.length()){
    		return recordId.substring(startingPosition,Math.min(startingPosition+length, recordId.length()));
    	}else{
    		return null;
    	}
    	
    }

}
