package it.gov.mef.noipa.postemissione.parser.autogenerated.cedolino.depcon.types;

public class TFRType {
	
	private String recordValue;

	public TFRType(String recordValue) {
		super();
		this.recordValue = recordValue;
	}
	
	public String getContrFondoGaranzia(){
		int startingPosition = 22;
    	int length = 13;
    	return getSubString(startingPosition, length);
	}
	
	public String getPrevComplementare(){
		int startingPosition = 55;
    	int length = 15;
    	return getSubString(startingPosition, length);
	}
	
	public String getValoreAccantonato(){
		int startingPosition = 89;
    	int length = 16;
    	return getSubString(startingPosition, length);
	}
	
	private String getSubString(int startingPosition, int length) {
		if(startingPosition<recordValue.length()){
    		return recordValue.substring(startingPosition,Math.min(startingPosition+length, recordValue.length())).trim();
    	}else{
    		return null;
    	}
	}

}
