//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.05 at 04:07:17 PM CET 
//


package it.gov.mef.noipa.postemissione.parser.autogenerated.cud.depcudcon;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.gov.mef.noipa.postemissione.parser.autogenerated.cud.depcudcon package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Main_QNAME = new QName("http://postemissione.noipa.mef.gov.it/parser/autogenerated/cud/depcudcon", "main");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.gov.mef.noipa.postemissione.parser.autogenerated.cud.depcudcon
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AnagraficaDipendente }
     * 
     */
    public AnagraficaDipendente createAnagraficaDipendente() {
        return new AnagraficaDipendente();
    }

    /**
     * Create an instance of {@link Inps }
     * 
     */
    public Inps createInps() {
        return new Inps();
    }

    /**
     * Create an instance of {@link DatiPrevidenzialiAssistenziali }
     * 
     */
    public DatiPrevidenzialiAssistenziali createDatiPrevidenzialiAssistenziali() {
        return new DatiPrevidenzialiAssistenziali();
    }

    /**
     * Create an instance of {@link AccontoConiuge }
     * 
     */
    public AccontoConiuge createAccontoConiuge() {
        return new AccontoConiuge();
    }

    /**
     * Create an instance of {@link OneriDeducibili }
     * 
     */
    public OneriDeducibili createOneriDeducibili() {
        return new OneriDeducibili();
    }

    /**
     * Create an instance of {@link Barcode }
     * 
     */
    public Barcode createBarcode() {
        return new Barcode();
    }

    /**
     * Create an instance of {@link TerzaPagina }
     * 
     */
    public TerzaPagina createTerzaPagina() {
        return new TerzaPagina();
    }

    /**
     * Create an instance of {@link Redditi }
     * 
     */
    public Redditi createRedditi() {
        return new Redditi();
    }

    /**
     * Create an instance of {@link DatiGenerali }
     * 
     */
    public DatiGenerali createDatiGenerali() {
        return new DatiGenerali();
    }

    /**
     * Create an instance of {@link CertificazioneLavAutonomo }
     * 
     */
    public CertificazioneLavAutonomo createCertificazioneLavAutonomo() {
        return new CertificazioneLavAutonomo();
    }

    /**
     * Create an instance of {@link TrattamentoFineRapporto }
     * 
     */
    public TrattamentoFineRapporto createTrattamentoFineRapporto() {
        return new TrattamentoFineRapporto();
    }

    /**
     * Create an instance of {@link AltriDati }
     * 
     */
    public AltriDati createAltriDati() {
        return new AltriDati();
    }

    /**
     * Create an instance of {@link PrevidenzaComplementare }
     * 
     */
    public PrevidenzaComplementare createPrevidenzaComplementare() {
        return new PrevidenzaComplementare();
    }

    /**
     * Create an instance of {@link ConiugeFamiliariDCA }
     * 
     */
    public ConiugeFamiliariDCA createConiugeFamiliariDCA() {
        return new ConiugeFamiliariDCA();
    }

    /**
     * Create an instance of {@link CompensiAnniPrecedenti }
     * 
     */
    public CompensiAnniPrecedenti createCompensiAnniPrecedenti() {
        return new CompensiAnniPrecedenti();
    }

    /**
     * Create an instance of {@link Annotazioni }
     * 
     */
    public Annotazioni createAnnotazioni() {
        return new Annotazioni();
    }

    /**
     * Create an instance of {@link CudDepcon }
     * 
     */
    public CudDepcon createCudDepcon() {
        return new CudDepcon();
    }

    /**
     * Create an instance of {@link DetrazioniCrediti }
     * 
     */
    public DetrazioniCrediti createDetrazioniCrediti() {
        return new DetrazioniCrediti();
    }

    /**
     * Create an instance of {@link Ritenute }
     * 
     */
    public Ritenute createRitenute() {
        return new Ritenute();
    }

    /**
     * Create an instance of {@link Inpdap }
     * 
     */
    public Inpdap createInpdap() {
        return new Inpdap();
    }

    /**
     * Create an instance of {@link BarcodeSecondaPagina }
     * 
     */
    public BarcodeSecondaPagina createBarcodeSecondaPagina() {
        return new BarcodeSecondaPagina();
    }

    /**
     * Create an instance of {@link Firma }
     * 
     */
    public Firma createFirma() {
        return new Firma();
    }

    /**
     * Create an instance of {@link ConiugeFamiliariCarico }
     * 
     */
    public ConiugeFamiliariCarico createConiugeFamiliariCarico() {
        return new ConiugeFamiliariCarico();
    }

    /**
     * Create an instance of {@link DatoreLavoro }
     * 
     */
    public DatoreLavoro createDatoreLavoro() {
        return new DatoreLavoro();
    }

    /**
     * Create an instance of {@link AccontoDichiarante }
     * 
     */
    public AccontoDichiarante createAccontoDichiarante() {
        return new AccontoDichiarante();
    }

    /**
     * Create an instance of {@link CUD2 }
     * 
     */
    public CUD2 createCUD2() {
        return new CUD2();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CudDepcon }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://postemissione.noipa.mef.gov.it/parser/autogenerated/cud/depcudcon", name = "main")
    public JAXBElement<CudDepcon> createMain(CudDepcon value) {
        return new JAXBElement<CudDepcon>(_Main_QNAME, CudDepcon.class, null, value);
    }

}
