//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.05 at 04:07:17 PM CET 
//


package it.gov.mef.noipa.postemissione.parser.autogenerated.cud.depcudcon;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Ritenute complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Ritenute">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="recordDF3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ritenuteIRPEFSopese" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ritenuteIRPEF" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="recordDF4" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="addizionaliRegionaliIRPEF" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="addizionaliComunaliIrpefAcconto20aa" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="addizionaliComunaliIrpefSaldo20aa" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="addizionaliComunaliIrpefAcconto20aa1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Ritenute", propOrder = {
    "recordDF3",
    "ritenuteIRPEFSopese",
    "ritenuteIRPEF",
    "recordDF4",
    "addizionaliRegionaliIRPEF",
    "addizionaliComunaliIrpefAcconto20Aa",
    "addizionaliComunaliIrpefSaldo20Aa",
    "addizionaliComunaliIrpefAcconto20Aa1"
})
@Generated(value = "com.sun.tools.xjc.Driver", date = "2016-02-05T04:07:17+01:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-2")
public class Ritenute {

    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2016-02-05T04:07:17+01:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-2")
    protected String recordDF3;
    @XmlElement(required = true, nillable = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2016-02-05T04:07:17+01:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-2")
    protected String ritenuteIRPEFSopese;
    @XmlElement(required = true, nillable = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2016-02-05T04:07:17+01:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-2")
    protected String ritenuteIRPEF;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2016-02-05T04:07:17+01:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-2")
    protected String recordDF4;
    @XmlElement(required = true, nillable = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2016-02-05T04:07:17+01:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-2")
    protected String addizionaliRegionaliIRPEF;
    @XmlElement(name = "addizionaliComunaliIrpefAcconto20aa", required = true, nillable = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2016-02-05T04:07:17+01:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-2")
    protected String addizionaliComunaliIrpefAcconto20Aa;
    @XmlElement(name = "addizionaliComunaliIrpefSaldo20aa", required = true, nillable = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2016-02-05T04:07:17+01:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-2")
    protected String addizionaliComunaliIrpefSaldo20Aa;
    @XmlElement(name = "addizionaliComunaliIrpefAcconto20aa1", required = true, nillable = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2016-02-05T04:07:17+01:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-2")
    protected String addizionaliComunaliIrpefAcconto20Aa1;

    /**
     * Gets the value of the recordDF3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2016-02-05T04:07:17+01:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-2")
    public String getRecordDF3() {
        return recordDF3;
    }

    /**
     * Sets the value of the recordDF3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2016-02-05T04:07:17+01:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-2")
    public void setRecordDF3(String value) {
        this.recordDF3 = value;
    }

    /**
     * Gets the value of the ritenuteIRPEFSopese property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2016-02-05T04:07:17+01:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-2")
    public String getRitenuteIRPEFSopese() {
        return ritenuteIRPEFSopese;
    }

    /**
     * Sets the value of the ritenuteIRPEFSopese property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2016-02-05T04:07:17+01:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-2")
    public void setRitenuteIRPEFSopese(String value) {
        this.ritenuteIRPEFSopese = value;
    }

    /**
     * Gets the value of the ritenuteIRPEF property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2016-02-05T04:07:17+01:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-2")
    public String getRitenuteIRPEF() {
        return ritenuteIRPEF;
    }

    /**
     * Sets the value of the ritenuteIRPEF property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2016-02-05T04:07:17+01:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-2")
    public void setRitenuteIRPEF(String value) {
        this.ritenuteIRPEF = value;
    }

    /**
     * Gets the value of the recordDF4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2016-02-05T04:07:17+01:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-2")
    public String getRecordDF4() {
        return recordDF4;
    }

    /**
     * Sets the value of the recordDF4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2016-02-05T04:07:17+01:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-2")
    public void setRecordDF4(String value) {
        this.recordDF4 = value;
    }

    /**
     * Gets the value of the addizionaliRegionaliIRPEF property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2016-02-05T04:07:17+01:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-2")
    public String getAddizionaliRegionaliIRPEF() {
        return addizionaliRegionaliIRPEF;
    }

    /**
     * Sets the value of the addizionaliRegionaliIRPEF property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2016-02-05T04:07:17+01:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-2")
    public void setAddizionaliRegionaliIRPEF(String value) {
        this.addizionaliRegionaliIRPEF = value;
    }

    /**
     * Gets the value of the addizionaliComunaliIrpefAcconto20Aa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2016-02-05T04:07:17+01:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-2")
    public String getAddizionaliComunaliIrpefAcconto20Aa() {
        return addizionaliComunaliIrpefAcconto20Aa;
    }

    /**
     * Sets the value of the addizionaliComunaliIrpefAcconto20Aa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2016-02-05T04:07:17+01:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-2")
    public void setAddizionaliComunaliIrpefAcconto20Aa(String value) {
        this.addizionaliComunaliIrpefAcconto20Aa = value;
    }

    /**
     * Gets the value of the addizionaliComunaliIrpefSaldo20Aa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2016-02-05T04:07:17+01:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-2")
    public String getAddizionaliComunaliIrpefSaldo20Aa() {
        return addizionaliComunaliIrpefSaldo20Aa;
    }

    /**
     * Sets the value of the addizionaliComunaliIrpefSaldo20Aa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2016-02-05T04:07:17+01:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-2")
    public void setAddizionaliComunaliIrpefSaldo20Aa(String value) {
        this.addizionaliComunaliIrpefSaldo20Aa = value;
    }

    /**
     * Gets the value of the addizionaliComunaliIrpefAcconto20Aa1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2016-02-05T04:07:17+01:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-2")
    public String getAddizionaliComunaliIrpefAcconto20Aa1() {
        return addizionaliComunaliIrpefAcconto20Aa1;
    }

    /**
     * Sets the value of the addizionaliComunaliIrpefAcconto20Aa1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2016-02-05T04:07:17+01:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-2")
    public void setAddizionaliComunaliIrpefAcconto20Aa1(String value) {
        this.addizionaliComunaliIrpefAcconto20Aa1 = value;
    }

}
