package it.gov.mef.noipa.postemissione.parser.autogenerated.cud.depcudcon.types;

public class DatiPrevAssType {
	protected String recordValue;

	public DatiPrevAssType(String recordValue) {
		super();
		this.recordValue = recordValue;
	}

	public String getRecordValue() {
		return recordValue;
	}

	public void setRecordValue(String value) {
		this.recordValue = value;
	}

	public String getMatricolaAzienda() {
		int startingPosition = 0;
		int length = 11;
		if (startingPosition < recordValue.length()) {
			return recordValue.substring(startingPosition,
					Math.min(startingPosition + length, recordValue.length()));
		} else {
			return null;
		}

	}

	public String getDesINPS() {
		int startingPosition = 11;
		int length = 1;
		if (startingPosition < recordValue.length()) {
			return recordValue.substring(startingPosition,
					Math.min(startingPosition + length, recordValue.length()));
		} else {
			return null;
		}

	}
	
	public String getAltro() {
		int startingPosition = 12;
		int length = 1;
		if (startingPosition < recordValue.length()) {
			return recordValue.substring(startingPosition,
					Math.min(startingPosition + length, recordValue.length()));
		} else {
			return null;
		}

	}
	
	public String getImponibilePrev() {
		int startingPosition = 13;
		int length = 13;
		if (startingPosition < recordValue.length()) {
			return recordValue.substring(startingPosition,
					Math.min(startingPosition + length, recordValue.length()));
		} else {
			return null;
		}

	}
	
	public String getContributoLavTrattenuti() {
		int startingPosition = 26;
		int length = 13;
		if (startingPosition < recordValue.length()) {
			return recordValue.substring(startingPosition,
					Math.min(startingPosition + length, recordValue.length()));
		} else {
			return null;
		}

	}
	
}
