package it.gov.mef.noipa.postemissione.parser.autogenerated.cud.depcudcon.types;


//<xs:element name="descrizioneEnte" type="xs:string" jrb:length="69"/>
//<xs:element name="codiceFiscale" type="xs:string"/> 

public class DG2Type {
	protected String recordValue;

	public DG2Type(String recordValue) {
		super();
		this.recordValue = recordValue;
	}

	public String getRecordValue() {
		return recordValue;
	}

	public void setRecordValue(String value) {
		this.recordValue = value;
	}

	public String getDescrizioneEnte() {
		int startingPosition = 0;
		int length = 69;
		if (startingPosition < recordValue.length()) {
			return recordValue.substring(startingPosition,
					Math.min(startingPosition + length, recordValue.length()));
		} else {
			return null;
		}
	}

	public String getCodiceFiscale() {
		int startingPosition = 69;
		if (startingPosition < recordValue.length()) {
			return recordValue.substring(startingPosition, recordValue.length());
		} else {
			return null;
		}
	}

}
