//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.05 at 04:07:19 PM CET 
//


package it.gov.mef.noipa.postemissione.parser.autogenerated.cud.cud;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.gov.mef.noipa.postemissione.parser.autogenerated.cud.cud package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.gov.mef.noipa.postemissione.parser.autogenerated.cud.cud
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CudType.DatiFiscali.DetrazioniCrediti.BonusIRPEF }
     * 
     */
    public CudType.DatiFiscali.DetrazioniCrediti.BonusIRPEF createCudTypeDatiFiscaliDetrazioniCreditiBonusIRPEF() {
        return new CudType.DatiFiscali.DetrazioniCrediti.BonusIRPEF();
    }

    /**
     * Create an instance of {@link CudType.Testata }
     * 
     */
    public CudType.Testata createCudTypeTestata() {
        return new CudType.Testata();
    }

    /**
     * Create an instance of {@link DettaglioAliquota }
     * 
     */
    public DettaglioAliquota createDettaglioAliquota() {
        return new DettaglioAliquota();
    }

    /**
     * Create an instance of {@link AnnotazioniType }
     * 
     */
    public AnnotazioniType createAnnotazioniType() {
        return new AnnotazioniType();
    }

    /**
     * Create an instance of {@link CudType.DatiFiscali.Acconti }
     * 
     */
    public CudType.DatiFiscali.Acconti createCudTypeDatiFiscaliAcconti() {
        return new CudType.DatiFiscali.Acconti();
    }

    /**
     * Create an instance of {@link AnagraficaType }
     * 
     */
    public AnagraficaType createAnagraficaType() {
        return new AnagraficaType();
    }

    /**
     * Create an instance of {@link CudType.DatiPrevidenziali.INPS }
     * 
     */
    public CudType.DatiPrevidenziali.INPS createCudTypeDatiPrevidenzialiINPS() {
        return new CudType.DatiPrevidenziali.INPS();
    }

    /**
     * Create an instance of {@link DomicilioFiscale }
     * 
     */
    public DomicilioFiscale createDomicilioFiscale() {
        return new DomicilioFiscale();
    }

    /**
     * Create an instance of {@link CudType.DatiFiscali.PrevidenzaComplementare }
     * 
     */
    public CudType.DatiFiscali.PrevidenzaComplementare createCudTypeDatiFiscaliPrevidenzaComplementare() {
        return new CudType.DatiFiscali.PrevidenzaComplementare();
    }

    /**
     * Create an instance of {@link CudType.DatiFiscali.DetrazioniCrediti }
     * 
     */
    public CudType.DatiFiscali.DetrazioniCrediti createCudTypeDatiFiscaliDetrazioniCrediti() {
        return new CudType.DatiFiscali.DetrazioniCrediti();
    }

    /**
     * Create an instance of {@link CudType }
     * 
     */
    public CudType createCudType() {
        return new CudType();
    }

    /**
     * Create an instance of {@link DettaglioImporto }
     * 
     */
    public DettaglioImporto createDettaglioImporto() {
        return new DettaglioImporto();
    }

    /**
     * Create an instance of {@link CudType.DatiFiscali.Redditi }
     * 
     */
    public CudType.DatiFiscali.Redditi createCudTypeDatiFiscaliRedditi() {
        return new CudType.DatiFiscali.Redditi();
    }

    /**
     * Create an instance of {@link CudType.Firma }
     * 
     */
    public CudType.Firma createCudTypeFirma() {
        return new CudType.Firma();
    }

    /**
     * Create an instance of {@link CudType.DatiFiscali.AltriDati }
     * 
     */
    public CudType.DatiFiscali.AltriDati createCudTypeDatiFiscaliAltriDati() {
        return new CudType.DatiFiscali.AltriDati();
    }

    /**
     * Create an instance of {@link CudType.Testata.EnteApp }
     * 
     */
    public CudType.Testata.EnteApp createCudTypeTestataEnteApp() {
        return new CudType.Testata.EnteApp();
    }

    /**
     * Create an instance of {@link CudType.CertificazioneLavoro }
     * 
     */
    public CudType.CertificazioneLavoro createCudTypeCertificazioneLavoro() {
        return new CudType.CertificazioneLavoro();
    }

    /**
     * Create an instance of {@link CudType.DatiGenerali.AnagraficaDipendente }
     * 
     */
    public CudType.DatiGenerali.AnagraficaDipendente createCudTypeDatiGeneraliAnagraficaDipendente() {
        return new CudType.DatiGenerali.AnagraficaDipendente();
    }

    /**
     * Create an instance of {@link CudType.DettaglioConiugeFamiliari }
     * 
     */
    public CudType.DettaglioConiugeFamiliari createCudTypeDettaglioConiugeFamiliari() {
        return new CudType.DettaglioConiugeFamiliari();
    }

    /**
     * Create an instance of {@link CudType.DatiGenerali.DatoreLavoro }
     * 
     */
    public CudType.DatiGenerali.DatoreLavoro createCudTypeDatiGeneraliDatoreLavoro() {
        return new CudType.DatiGenerali.DatoreLavoro();
    }

    /**
     * Create an instance of {@link CudType.SezDestinazione }
     * 
     */
    public CudType.SezDestinazione createCudTypeSezDestinazione() {
        return new CudType.SezDestinazione();
    }

    /**
     * Create an instance of {@link CudType.DatiFiscali.OneriDeducibili }
     * 
     */
    public CudType.DatiFiscali.OneriDeducibili createCudTypeDatiFiscaliOneriDeducibili() {
        return new CudType.DatiFiscali.OneriDeducibili();
    }

    /**
     * Create an instance of {@link CudType.DatiFiscali }
     * 
     */
    public CudType.DatiFiscali createCudTypeDatiFiscali() {
        return new CudType.DatiFiscali();
    }

    /**
     * Create an instance of {@link CudType.TestoAnnotazioni }
     * 
     */
    public CudType.TestoAnnotazioni createCudTypeTestoAnnotazioni() {
        return new CudType.TestoAnnotazioni();
    }

    /**
     * Create an instance of {@link AccontiAP }
     * 
     */
    public AccontiAP createAccontiAP() {
        return new AccontiAP();
    }

    /**
     * Create an instance of {@link ConiugeFamiliariCaricoType }
     * 
     */
    public ConiugeFamiliariCaricoType createConiugeFamiliariCaricoType() {
        return new ConiugeFamiliariCaricoType();
    }

    /**
     * Create an instance of {@link CudType.DatiPrevidenziali }
     * 
     */
    public CudType.DatiPrevidenziali createCudTypeDatiPrevidenziali() {
        return new CudType.DatiPrevidenziali();
    }

    /**
     * Create an instance of {@link CudType.TassazioneSeparata }
     * 
     */
    public CudType.TassazioneSeparata createCudTypeTassazioneSeparata() {
        return new CudType.TassazioneSeparata();
    }

    /**
     * Create an instance of {@link IndirizzoType }
     * 
     */
    public IndirizzoType createIndirizzoType() {
        return new IndirizzoType();
    }

    /**
     * Create an instance of {@link CudType.DatiGenerali }
     * 
     */
    public CudType.DatiGenerali createCudTypeDatiGenerali() {
        return new CudType.DatiGenerali();
    }

    /**
     * Create an instance of {@link CudType.TassazioneSeparata.CompensiAnniPrecedenti }
     * 
     */
    public CudType.TassazioneSeparata.CompensiAnniPrecedenti createCudTypeTassazioneSeparataCompensiAnniPrecedenti() {
        return new CudType.TassazioneSeparata.CompensiAnniPrecedenti();
    }

    /**
     * Create an instance of {@link CudType.DatiPrevidenziali.INPDAP }
     * 
     */
    public CudType.DatiPrevidenziali.INPDAP createCudTypeDatiPrevidenzialiINPDAP() {
        return new CudType.DatiPrevidenziali.INPDAP();
    }

    /**
     * Create an instance of {@link TotaliINPDAP }
     * 
     */
    public TotaliINPDAP createTotaliINPDAP() {
        return new TotaliINPDAP();
    }

    /**
     * Create an instance of {@link CudType.TassazioneSeparata.TFR }
     * 
     */
    public CudType.TassazioneSeparata.TFR createCudTypeTassazioneSeparataTFR() {
        return new CudType.TassazioneSeparata.TFR();
    }

    /**
     * Create an instance of {@link Cud }
     * 
     */
    public Cud createCud() {
        return new Cud();
    }

    /**
     * Create an instance of {@link MatricolaType }
     * 
     */
    public MatricolaType createMatricolaType() {
        return new MatricolaType();
    }

    /**
     * Create an instance of {@link CudType.CertificazioneLavoro.DatiCertificazione }
     * 
     */
    public CudType.CertificazioneLavoro.DatiCertificazione createCudTypeCertificazioneLavoroDatiCertificazione() {
        return new CudType.CertificazioneLavoro.DatiCertificazione();
    }

    /**
     * Create an instance of {@link DenunciaUniemens }
     * 
     */
    public DenunciaUniemens createDenunciaUniemens() {
        return new DenunciaUniemens();
    }

    /**
     * Create an instance of {@link CudType.DatiFiscali.Ritenute }
     * 
     */
    public CudType.DatiFiscali.Ritenute createCudTypeDatiFiscaliRitenute() {
        return new CudType.DatiFiscali.Ritenute();
    }

}
