//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.05 at 04:07:18 PM CET 
//


package it.gov.mef.noipa.postemissione.parser.autogenerated.cedolino.cedolino;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.gov.mef.noipa.postemissione.parser.autogenerated.cedolino.cedolino package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.gov.mef.noipa.postemissione.parser.autogenerated.cedolino.cedolino
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CedolinoType.PosGiurEco }
     * 
     */
    public CedolinoType.PosGiurEco createCedolinoTypePosGiurEco() {
        return new CedolinoType.PosGiurEco();
    }

    /**
     * Create an instance of {@link CedolinoType.PerContoDi }
     * 
     */
    public CedolinoType.PerContoDi createCedolinoTypePerContoDi() {
        return new CedolinoType.PerContoDi();
    }

    /**
     * Create an instance of {@link CedolinoType.RiepilogoRetribuzione.DatiRiepilogoRetribuzione.Competenze }
     * 
     */
    public CedolinoType.RiepilogoRetribuzione.DatiRiepilogoRetribuzione.Competenze createCedolinoTypeRiepilogoRetribuzioneDatiRiepilogoRetribuzioneCompetenze() {
        return new CedolinoType.RiepilogoRetribuzione.DatiRiepilogoRetribuzione.Competenze();
    }

    /**
     * Create an instance of {@link CedolinoType.Testata }
     * 
     */
    public CedolinoType.Testata createCedolinoTypeTestata() {
        return new CedolinoType.Testata();
    }

    /**
     * Create an instance of {@link CedolinoType.DettaglioRetribuzione.GruppoDettaglioRetribuzione }
     * 
     */
    public CedolinoType.DettaglioRetribuzione.GruppoDettaglioRetribuzione createCedolinoTypeDettaglioRetribuzioneGruppoDettaglioRetribuzione() {
        return new CedolinoType.DettaglioRetribuzione.GruppoDettaglioRetribuzione();
    }

    /**
     * Create an instance of {@link CedolinoType.DettaglioRetribuzione.GruppoDettaglioRetribuzione.DatiDettaglioRetribuzione }
     * 
     */
    public CedolinoType.DettaglioRetribuzione.GruppoDettaglioRetribuzione.DatiDettaglioRetribuzione createCedolinoTypeDettaglioRetribuzioneGruppoDettaglioRetribuzioneDatiDettaglioRetribuzione() {
        return new CedolinoType.DettaglioRetribuzione.GruppoDettaglioRetribuzione.DatiDettaglioRetribuzione();
    }

    /**
     * Create an instance of {@link CedolinoType.DettaglioRetribuzione.GruppoDettaglioRetribuzione.DatiDettaglioRetribuzione.DettaglioCompetenze }
     * 
     */
    public CedolinoType.DettaglioRetribuzione.GruppoDettaglioRetribuzione.DatiDettaglioRetribuzione.DettaglioCompetenze createCedolinoTypeDettaglioRetribuzioneGruppoDettaglioRetribuzioneDatiDettaglioRetribuzioneDettaglioCompetenze() {
        return new CedolinoType.DettaglioRetribuzione.GruppoDettaglioRetribuzione.DatiDettaglioRetribuzione.DettaglioCompetenze();
    }

    /**
     * Create an instance of {@link CedolinoType.RiepilogoRetribuzione.DatiRiepilogoRetribuzione.Ritenute }
     * 
     */
    public CedolinoType.RiepilogoRetribuzione.DatiRiepilogoRetribuzione.Ritenute createCedolinoTypeRiepilogoRetribuzioneDatiRiepilogoRetribuzioneRitenute() {
        return new CedolinoType.RiepilogoRetribuzione.DatiRiepilogoRetribuzione.Ritenute();
    }

    /**
     * Create an instance of {@link CedolinoType }
     * 
     */
    public CedolinoType createCedolinoType() {
        return new CedolinoType();
    }

    /**
     * Create an instance of {@link CedolinoType.ContrattiVigenti }
     * 
     */
    public CedolinoType.ContrattiVigenti createCedolinoTypeContrattiVigenti() {
        return new CedolinoType.ContrattiVigenti();
    }

    /**
     * Create an instance of {@link CedolinoType.RiepilogoRetribuzione.DatiRiepilogoRetribuzione }
     * 
     */
    public CedolinoType.RiepilogoRetribuzione.DatiRiepilogoRetribuzione createCedolinoTypeRiepilogoRetribuzioneDatiRiepilogoRetribuzione() {
        return new CedolinoType.RiepilogoRetribuzione.DatiRiepilogoRetribuzione();
    }

    /**
     * Create an instance of {@link IndirizzoType }
     * 
     */
    public IndirizzoType createIndirizzoType() {
        return new IndirizzoType();
    }

    /**
     * Create an instance of {@link CedolinoType.Messaggi }
     * 
     */
    public CedolinoType.Messaggi createCedolinoTypeMessaggi() {
        return new CedolinoType.Messaggi();
    }

    /**
     * Create an instance of {@link CedolinoType.DettDetrazioni }
     * 
     */
    public CedolinoType.DettDetrazioni createCedolinoTypeDettDetrazioni() {
        return new CedolinoType.DettDetrazioni();
    }

    /**
     * Create an instance of {@link CedolinoType.Progressivi }
     * 
     */
    public CedolinoType.Progressivi createCedolinoTypeProgressivi() {
        return new CedolinoType.Progressivi();
    }

    /**
     * Create an instance of {@link Cedolini }
     * 
     */
    public Cedolini createCedolini() {
        return new Cedolini();
    }

    /**
     * Create an instance of {@link DettaglioAliquota }
     * 
     */
    public DettaglioAliquota createDettaglioAliquota() {
        return new DettaglioAliquota();
    }

    /**
     * Create an instance of {@link CedolinoType.DettaglioRetribuzione }
     * 
     */
    public CedolinoType.DettaglioRetribuzione createCedolinoTypeDettaglioRetribuzione() {
        return new CedolinoType.DettaglioRetribuzione();
    }

    /**
     * Create an instance of {@link CedolinoType.RiepilogoRetribuzione }
     * 
     */
    public CedolinoType.RiepilogoRetribuzione createCedolinoTypeRiepilogoRetribuzione() {
        return new CedolinoType.RiepilogoRetribuzione();
    }

    /**
     * Create an instance of {@link AnagraficaType }
     * 
     */
    public AnagraficaType createAnagraficaType() {
        return new AnagraficaType();
    }

    /**
     * Create an instance of {@link CedolinoType.Tfr }
     * 
     */
    public CedolinoType.Tfr createCedolinoTypeTfr() {
        return new CedolinoType.Tfr();
    }

    /**
     * Create an instance of {@link CedolinoType.DettaglioRetribuzione.GruppoDettaglioRetribuzione.DatiDettaglioRetribuzione.DettaglioRitenute }
     * 
     */
    public CedolinoType.DettaglioRetribuzione.GruppoDettaglioRetribuzione.DatiDettaglioRetribuzione.DettaglioRitenute createCedolinoTypeDettaglioRetribuzioneGruppoDettaglioRetribuzioneDatiDettaglioRetribuzioneDettaglioRitenute() {
        return new CedolinoType.DettaglioRetribuzione.GruppoDettaglioRetribuzione.DatiDettaglioRetribuzione.DettaglioRitenute();
    }

    /**
     * Create an instance of {@link MatricolaType }
     * 
     */
    public MatricolaType createMatricolaType() {
        return new MatricolaType();
    }

    /**
     * Create an instance of {@link CedolinoType.EstrPagam }
     * 
     */
    public CedolinoType.EstrPagam createCedolinoTypeEstrPagam() {
        return new CedolinoType.EstrPagam();
    }

    /**
     * Create an instance of {@link CedolinoType.Testata.EnteApp }
     * 
     */
    public CedolinoType.Testata.EnteApp createCedolinoTypeTestataEnteApp() {
        return new CedolinoType.Testata.EnteApp();
    }

    /**
     * Create an instance of {@link DettaglioImporto }
     * 
     */
    public DettaglioImporto createDettaglioImporto() {
        return new DettaglioImporto();
    }

    /**
     * Create an instance of {@link CedolinoType.Totali }
     * 
     */
    public CedolinoType.Totali createCedolinoTypeTotali() {
        return new CedolinoType.Totali();
    }

}
