//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.12.15 at 06:18:33 PM CET
//
package it.gov.mef.noipa.postemissione.parser.autogenerated.cedolino;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for AnagraficaType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="AnagraficaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cognome" type="{https://noipa.mef.gov.it/schema/definizioneTipiSemplici.xsd}String50Type"/>
 *         &lt;element name="nome" type="{https://noipa.mef.gov.it/schema/definizioneTipiSemplici.xsd}String50Type"/>
 *         &lt;element name="dataNascita" type="{https://noipa.mef.gov.it/schema/definizioneTipiSemplici.xsd}DATA_TYPE"/>
 *         &lt;element name="domicilio_fiscale" type="{https://noipa.mef.gov.it/schema/definizioneTipiSemplici.xsd}STRINGA80_TYPE"/>
 *         &lt;element name="matricola" type="{https://noipa.mef.gov.it/schema/definizioneTipiSemplici.xsd}MatricolaType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="CodFiscaleAmministrato" use="required" type="{https://noipa.mef.gov.it/schema/definizioneTipiSemplici.xsd}CodiceFiscaleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AnagraficaType", propOrder = {
	"cognome",
	"nome",
	"dataNascita",
	"domicilioFiscale",
	"matricola"
})
public class AnagraficaType {

	@XmlElement(required = true)
	protected String cognome;
	@XmlElement(required = true)
	protected String nome;
	@XmlElement(required = true)
	protected String dataNascita;
	@XmlElement(name = "domicilio_fiscale", required = true)
	protected String domicilioFiscale;
	@XmlElement(required = true)
	protected MatricolaType matricola;
	@XmlAttribute(name = "CodFiscaleAmministrato", required = true)
	protected String codFiscaleAmministrato;

	/**
	 * Gets the value of the cognome property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getCognome() {
		return cognome;
	}

	/**
	 * Sets the value of the cognome property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setCognome(String value) {
		this.cognome = value;
	}

	/**
	 * Gets the value of the nome property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getNome() {
		return nome;
	}

	/**
	 * Sets the value of the nome property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setNome(String value) {
		this.nome = value;
	}

	/**
	 * Gets the value of the dataNascita property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getDataNascita() {
		return dataNascita;
	}

	/**
	 * Sets the value of the dataNascita property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setDataNascita(String value) {
		this.dataNascita = value;
	}

	/**
	 * Gets the value of the domicilioFiscale property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getDomicilioFiscale() {
		return domicilioFiscale;
	}

	/**
	 * Sets the value of the domicilioFiscale property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setDomicilioFiscale(String value) {
		this.domicilioFiscale = value;
	}

	/**
	 * Gets the value of the matricola property.
	 *
	 * @return possible object is {@link MatricolaType }
	 *
	 */
	public MatricolaType getMatricola() {
		return matricola;
	}

	/**
	 * Sets the value of the matricola property.
	 *
	 * @param value allowed object is {@link MatricolaType }
	 *
	 */
	public void setMatricola(MatricolaType value) {
		this.matricola = value;
	}

	/**
	 * Gets the value of the codFiscaleAmministrato property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getCodFiscaleAmministrato() {
		return codFiscaleAmministrato;
	}

	/**
	 * Sets the value of the codFiscaleAmministrato property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setCodFiscaleAmministrato(String value) {
		this.codFiscaleAmministrato = value;
	}

}
