//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.12.15 at 06:18:33 PM CET
//
package it.gov.mef.noipa.postemissione.parser.autogenerated.cedolino;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Riga di dettaglio Competenze/Ritenute sul riepilogo
 *
 * <p>
 * Java class for DettaglioAliquota complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="DettaglioAliquota">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="descrizione" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="importo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="imponibile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="aliquota" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DettaglioAliquota", propOrder = {
	"descrizione",
	"importo",
	"imponibile",
	"aliquota"
})
public class DettaglioAliquota {

	protected String descrizione;
	@XmlElement(required = true)
	protected String importo;
	@XmlElement(required = true)
	protected String imponibile;
	@XmlElement(required = true)
	protected String aliquota;

	/**
	 * Gets the value of the descrizione property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getDescrizione() {
		return descrizione;
	}

	/**
	 * Sets the value of the descrizione property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setDescrizione(String value) {
		this.descrizione = value;
	}

	/**
	 * Gets the value of the importo property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getImporto() {
		return importo;
	}

	/**
	 * Sets the value of the importo property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setImporto(String value) {
		this.importo = value;
	}

	/**
	 * Gets the value of the imponibile property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getImponibile() {
		return imponibile;
	}

	/**
	 * Sets the value of the imponibile property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setImponibile(String value) {
		this.imponibile = value;
	}

	/**
	 * Gets the value of the aliquota property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getAliquota() {
		return aliquota;
	}

	/**
	 * Sets the value of the aliquota property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setAliquota(String value) {
		this.aliquota = value;
	}

}
