package it.gov.mef.noipa.postemissione.pe_xmlloaderbatch.batch.bean;

import it.gov.mef.noipa.postemissione.parser.autogenerated.cedolino.CedolinoType;

public class CedolinoDocument {

	private boolean visibile;
	private boolean archiviato;

	private int idPostemissione;
	private String sistemaProvenienza;

	private String idCentera;

	private String pathFile;
	private String nomeFile;

	private String codTipologiaEmissione;
	private String descTipologiaEmissione;

	private CedolinoType document;
	private String dataProduzione;

	public CedolinoDocument() {
		super();
	}

	public CedolinoDocument(boolean visibile, boolean archiviato,
			int idPostemissione, String idCentera,
			String nomeFileXml, String codTipologiaEmissione, String descTipologiaEmissione, String dataProduzione, String sistemaProvenienza, CedolinoType cedolino) {
		super();
		this.visibile = visibile;
		this.archiviato = archiviato;
		this.idPostemissione = idPostemissione;
		this.idCentera = idCentera;
		this.nomeFile = nomeFileXml;
		this.codTipologiaEmissione = codTipologiaEmissione;
		this.descTipologiaEmissione = descTipologiaEmissione;
		this.dataProduzione = dataProduzione;
		this.sistemaProvenienza = sistemaProvenienza;
		this.setDocument(cedolino);
	}

	public boolean isArchiviato() {
		return archiviato;
	}

	public void setArchiviato(boolean archiviato) {
		this.archiviato = archiviato;
	}

	public String getIdCentera() {
		return idCentera;
	}

	public void setIdCentera(String idCentera) {
		this.idCentera = idCentera;
	}

	public String getNomeFile() {
		return nomeFile;
	}

	public void setNomeFile(String nomeFile) {
		this.nomeFile = nomeFile;
	}

	public String getPathFile() {
		return pathFile;
	}

	public void setPathFile(String pathFile) {
		this.pathFile = pathFile;
	}

	public void setIdPostemissione(int idPostemissione) {
		this.idPostemissione = idPostemissione;
	}

	public int getIdPostemissione() {
		return idPostemissione;
	}

	public boolean isVisibile() {
		return visibile;
	}

	public void setVisibile(boolean visibile) {
		this.visibile = visibile;
	}

	public String getCodTipologiaEmissione() {
		return codTipologiaEmissione;
	}

	public void setCodTipologiaEmissione(String codTipologiaEmissione) {
		this.codTipologiaEmissione = codTipologiaEmissione;
	}

	public String getDescTipologiaEmissione() {
		return descTipologiaEmissione;
	}

	public void setDescTipologiaEmissione(String descTipologiaEmissione) {
		this.descTipologiaEmissione = descTipologiaEmissione;
	}

	public CedolinoType getDocument() {
		return document;
	}

	public void setDocument(CedolinoType document) {
		this.document = document;
	}

	public String getDataProduzione() {
		return dataProduzione;
	}

	public void setDataProduzione(String dataProduzione) {
		this.dataProduzione = dataProduzione;
	}

	public String getSistemaProvenienza() {
		return sistemaProvenienza;
	}

	public void setSistemaProvenienza(String sistemaProvenienza) {
		this.sistemaProvenienza = sistemaProvenienza;
	}

}
