package it.gov.mef.noipa.postemissione.pe_xmlloaderbatch.batch.bean;

import it.gov.mef.noipa.postemissione.parser.autogenerated.cud.CudType;

public class CudDocument {

	private boolean visibile;
	private boolean archiviato;

	private int idPostemissione;

	private String idCentera;

	private String pathFile;
	private String nomeFile;

	private String codTipologiaEmissione;
	private String descTipologiaEmissione;

	private CudType document;

	public CudDocument() {
		super();
	}

	public CudDocument(boolean visibile, boolean archiviato,
			int idPostemissione, String idCentera,
			String nomeFileXml, String codTipologiaEmissione, String descTipologiaEmissione, CudType cud) {
		super();
		this.visibile = visibile;
		this.archiviato = archiviato;
		this.idPostemissione = idPostemissione;
		this.idCentera = idCentera;
		this.nomeFile = nomeFileXml;
		this.codTipologiaEmissione = codTipologiaEmissione;
		this.descTipologiaEmissione = descTipologiaEmissione;
		this.document = cud;
	}

	public boolean isArchiviato() {
		return archiviato;
	}

	public void setArchiviato(boolean archiviato) {
		this.archiviato = archiviato;
	}

	public String getIdCentera() {
		return idCentera;
	}

	public void setIdCentera(String idCentera) {
		this.idCentera = idCentera;
	}

	public String getNomeFile() {
		return nomeFile;
	}

	public void setNomeFile(String nomeFile) {
		this.nomeFile = nomeFile;
	}

	public String getPathFile() {
		return pathFile;
	}

	public void setPathFile(String pathFile) {
		this.pathFile = pathFile;
	}

	public void setIdPostemissione(int idPostemissione) {
		this.idPostemissione = idPostemissione;
	}

	public int getIdPostemissione() {
		return idPostemissione;
	}

	public boolean isVisibile() {
		return visibile;
	}

	public void setVisibile(boolean visibile) {
		this.visibile = visibile;
	}

	public String getCodTipologiaEmissione() {
		return codTipologiaEmissione;
	}

	public void setCodTipologiaEmissione(String codTipologiaEmissione) {
		this.codTipologiaEmissione = codTipologiaEmissione;
	}

	public String getDescTipologiaEmissione() {
		return descTipologiaEmissione;
	}

	public void setDescTipologiaEmissione(String descTipologiaEmissione) {
		this.descTipologiaEmissione = descTipologiaEmissione;
	}

	public CudType getDocument() {
		return document;
	}

	public void setDocument(CudType document) {
		this.document = document;
	}

}
