package it.gov.mef.noipa.postemissione.pe_xmlloaderbatch.batch.bean;

import java.util.Date;

import org.apache.log4j.Logger;

public class PostEmissioneDocument {

	private static final Logger LOGGER = Logger.getLogger(PostEmissioneDocument.class);
	private int idSottosistema;
	private int idDocumento;
	private String descrizioneSottosistema;
	private int rata;
	private int progEmissione;
	private String codEmissione;
	private boolean pubblicato;
	private Date dataEmissione;

	public PostEmissioneDocument() {
		super();
	}

	public PostEmissioneDocument(int idSottosistema,
			String descrizioneSottosistema, int rata, int progEmissione,
			String codEmissione, Date dataEmissione, boolean pubblicato, int idDocumento) {
		super();
		this.idSottosistema = idSottosistema;
		this.descrizioneSottosistema = descrizioneSottosistema;
		this.rata = rata;
		this.progEmissione = progEmissione;
		this.codEmissione = codEmissione;
		this.pubblicato = pubblicato;
		this.dataEmissione = dataEmissione;
		this.idDocumento = idDocumento;
	}

	public int getIdSottosistema() {
		return idSottosistema;
	}

	public void setIdSottosistema(int idSottosistema) {
		this.idSottosistema = idSottosistema;
	}

	public String getDescrizioneSottosistema() {
		return descrizioneSottosistema;
	}

	public void setDescrizioneSottosistema(String descrizioneSottosistema) {
		this.descrizioneSottosistema = descrizioneSottosistema;
	}

	public int getRata() {
		return rata;
	}

	public void setRata(int rata) {
		this.rata = rata;
	}

	public int getProgEmissione() {
		return progEmissione;
	}

	public void setProgEmissione(int progEmissione) {
		this.progEmissione = progEmissione;
	}

	public String getCodEmissione() {
		return codEmissione;
	}

	public void setCodEmissione(String codEmissione) {
		this.codEmissione = codEmissione;
	}

	public boolean isPubblicato() {
		return pubblicato;
	}

	public void setPubblicato(boolean pubblicato) {
		this.pubblicato = pubblicato;
	}

	public Date getDataEmissione() {
		return dataEmissione;
	}

	public void setDataEmissione(Date dataEmissione) {
		this.dataEmissione = dataEmissione;
	}

	public int getIdDocumento() {
		return idDocumento;
	}

	public void setIdDocumento(int idDocumento) {
		this.idDocumento = idDocumento;
	}

	public String getTypeDocumento() {
		if (idDocumento == 1) {
			return "cedolino";
		}
		if (idDocumento == 2) { // a.orfeo cu 2018 
			LOGGER.info(">>> getTypeDocumento() [cu]");
			return "cu";
		}
		return null;
	}

	public String getRootElement() {
		if (idDocumento == 1) {
			return "cedolini";
		}
		if (idDocumento == 2) { // a.orfeo cu 2018 
			LOGGER.info(">>> getRootElement() [cu]");
			return "cu"; 
		}
		return null;
	}

	public String getPathRootElement() {
		if (idDocumento == 1) {
			return "it.gov.mef.noipa.postemissione.parser.autogenerated.cedolino.Cedolini";
		}
		if (idDocumento == 2) { // a.orfeo cu 2018
			LOGGER.info(">>> getPathRootElement() [it.gov.mef.noipa.postemissione.parser.autogenerated.cu.cu.Cedolini");
			return "it.gov.mef.noipa.postemissione.parser.autogenerated.cu.cu.Cedolini"; 
		}
		return null;
	}

	public String getSchemaLocation() {
		if (idDocumento == 1) {
			return "/cedolino/Cedolino.xsd";
		}
		if (idDocumento == 2) { // a.orfeo cu 2018
			LOGGER.info(">>> getSchemaLocation() [/cu/CU.xsd]");
			return "/cu/CU.xsd";
		}
		return null;
	}

}
