//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.12.15 at 06:18:34 PM CET
//
package it.gov.mef.noipa.postemissione.parser.autogenerated.cud;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for AccontiAP complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="AccontiAP">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="primo_acc_Irpef_tratt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="secondo_acc._Irpef" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="acc_IRPEF_sospesi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="acc_addComunale_Irpef" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="acc_addComunale_Irpef_sosp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="prima_rata_acc_cedSecca" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="seconda_rata_acc_cedSecca" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AccontiAP", propOrder = {
	"primoAccIrpefTratt",
	"secondoAccIrpef",
	"accIRPEFSospesi",
	"accAddComunaleIrpef",
	"accAddComunaleIrpefSosp",
	"primaRataAccCedSecca",
	"secondaRataAccCedSecca"
})
public class AccontiAP {

	@XmlElement(name = "primo_acc_Irpef_tratt")
	protected String primoAccIrpefTratt;
	@XmlElement(name = "secondo_acc._Irpef")
	protected String secondoAccIrpef;
	@XmlElement(name = "acc_IRPEF_sospesi")
	protected String accIRPEFSospesi;
	@XmlElement(name = "acc_addComunale_Irpef")
	protected String accAddComunaleIrpef;
	@XmlElement(name = "acc_addComunale_Irpef_sosp")
	protected String accAddComunaleIrpefSosp;
	@XmlElement(name = "prima_rata_acc_cedSecca")
	protected String primaRataAccCedSecca;
	@XmlElement(name = "seconda_rata_acc_cedSecca")
	protected String secondaRataAccCedSecca;

	/**
	 * Gets the value of the primoAccIrpefTratt property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getPrimoAccIrpefTratt() {
		return primoAccIrpefTratt;
	}

	/**
	 * Sets the value of the primoAccIrpefTratt property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setPrimoAccIrpefTratt(String value) {
		this.primoAccIrpefTratt = value;
	}

	/**
	 * Gets the value of the secondoAccIrpef property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getSecondoAccIrpef() {
		return secondoAccIrpef;
	}

	/**
	 * Sets the value of the secondoAccIrpef property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setSecondoAccIrpef(String value) {
		this.secondoAccIrpef = value;
	}

	/**
	 * Gets the value of the accIRPEFSospesi property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getAccIRPEFSospesi() {
		return accIRPEFSospesi;
	}

	/**
	 * Sets the value of the accIRPEFSospesi property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setAccIRPEFSospesi(String value) {
		this.accIRPEFSospesi = value;
	}

	/**
	 * Gets the value of the accAddComunaleIrpef property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getAccAddComunaleIrpef() {
		return accAddComunaleIrpef;
	}

	/**
	 * Sets the value of the accAddComunaleIrpef property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setAccAddComunaleIrpef(String value) {
		this.accAddComunaleIrpef = value;
	}

	/**
	 * Gets the value of the accAddComunaleIrpefSosp property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getAccAddComunaleIrpefSosp() {
		return accAddComunaleIrpefSosp;
	}

	/**
	 * Sets the value of the accAddComunaleIrpefSosp property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setAccAddComunaleIrpefSosp(String value) {
		this.accAddComunaleIrpefSosp = value;
	}

	/**
	 * Gets the value of the primaRataAccCedSecca property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getPrimaRataAccCedSecca() {
		return primaRataAccCedSecca;
	}

	/**
	 * Sets the value of the primaRataAccCedSecca property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setPrimaRataAccCedSecca(String value) {
		this.primaRataAccCedSecca = value;
	}

	/**
	 * Gets the value of the secondaRataAccCedSecca property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getSecondaRataAccCedSecca() {
		return secondaRataAccCedSecca;
	}

	/**
	 * Sets the value of the secondaRataAccCedSecca property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setSecondaRataAccCedSecca(String value) {
		this.secondaRataAccCedSecca = value;
	}

}
