package it.gov.mef.noipa.postemissione.pe_depconconverterbatch.batch.cud;

import it.assist.jrecordbind.CudReader;
import it.assist.jrecordbind.Unmarshaller;
import it.gov.mef.noipa.postemissione.parser.autogenerated.cedolino.depcon.CedolinoDepcon;
import it.gov.mef.noipa.postemissione.parser.autogenerated.cud.depcudcon.CudDepcon;

import java.io.FileInputStream;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.Date;
import java.util.Iterator;

import org.apache.log4j.Logger;
import org.springframework.batch.item.ExecutionContext;
import org.springframework.batch.item.ItemStreamException;
import org.springframework.batch.item.file.ResourceAwareItemReaderItemStream;
import org.springframework.core.io.Resource;


public class Reader implements ResourceAwareItemReaderItemStream<CudDepcon> {

	private static final Logger LOGGER = Logger.getLogger(Reader.class);
	
	private Resource resource;
	private Iterator<CudDepcon> iter;
	private InputStreamReader isr;
	private FileInputStream fis;
	Date timeStart = new Date();
	
	public CudDepcon read() throws Exception {
		
		if (iter == null){
			Date timeMarshall = new Date();
			Unmarshaller<CudDepcon> unmarshaller;
			InputStream isXsd = Reader.class.getResourceAsStream("/cuddepcon/depcudcon.def.xsd");
			InputStreamReader isrXsd = new InputStreamReader(isXsd);
			
			unmarshaller = new Unmarshaller<CudDepcon>(isrXsd, CudReader.class.getName());
			fis = new FileInputStream(resource.getFile().getPath());
			isr = new InputStreamReader(fis);
			iter = unmarshaller.unmarshall(isr);
			
			isrXsd.close();
			isXsd.close();
			LOGGER.info("Tempo unmarshall:" + (new Date().getTime() - timeMarshall.getTime() ));
		}

		if (iter.hasNext()){
			CudDepcon result = iter.next();
			return result;
		}else {
			LOGGER.info("Tempo totale Iterator:" + (new Date().getTime() - timeStart.getTime() ));
			isr.close();
			fis.close();
			return null;
		}
	}


	public void setResource(Resource arg0) {
		resource = arg0;
	}


	public void close() throws ItemStreamException {
		LOGGER.info("close Reader");
	}


	public void open(ExecutionContext arg0) throws ItemStreamException {
		LOGGER.info("open Reader");
	}


	public void update(ExecutionContext arg0) throws ItemStreamException {
		LOGGER.info("update Reader");
	}


	public Iterator<CudDepcon> getIter() {
		return iter;
	}


	public void setIter(Iterator<CudDepcon> iter) {
		this.iter = iter;
	}

}
